USE master;
GO 


CREATE DATABASE TURISMO 
ON ( 
	NAME = TURISMO, 
	FILENAME = 'E:\SQLServerDB\TURISMO.mdf', 
	SIZE = 10, 
	MAXSIZE = 50, 
	FILEGROWTH = 5 
) 
LOG ON ( 
	NAME = TURISMOLOG, 
	FILENAME = 'E:\SQLServerDB\TURISMOLOG.ldf', 
	SIZE = 5MB, 
	MAXSIZE = 25MB, 
	FILEGROWTH = 5MB 
); 
GO

CREATE TABLE TURISMO..PRUEBA(
	ID INT IDENTITY PRIMARY KEY,
	DATO VARCHAR(1000)
);
GO

WHILE(1=1)
BEGIN
	INSERT INTO TURISMO..PRUEBA(DATO) VALUES('SQL SERVER ES LO MAXIMO');
END;
GO

